<?php
/** =========================================================================== **/
/* > Utilities
/** =========================================================================== **/

Abstract Class Utilities 
{

	/**
	 * add_js
	 *
	 * The build script automatically combines and minifies javascript files found
	 * in the footer so in order to preserve the use of the wp_enqueue_script / wp_register_script
	 * we can pass the js file generated by the build script to this function
	 *
	 * @param path 
	 * @param deps (mixed) comma delimited str or array list of dependencies
	 * @param in_footer (bool) true to load the js in the head  
	 */
	public static function add_js($path, $deps=NULL, $in_footer=true)
	{

		$is_fullpath = false;
		if ( strpos($path, 'http') !== false )
			$is_fullpath = true;

		// Create the name for registration. This uses the script file name to create the name
		// for registration. To create the name we strip out the file type, the version number, and
		// any special characters.For example if the script file name is 'jquery.test-1.1.min.js'
		// the name would be 'jquerytest'.
		$pos = strrpos($path, '/') + 1;
		$name = Utilities::slice_string($path, $pos );
		$name= preg_replace("/((-[0-9.]+)?(.min)?(.js)$)/", '', $name);
		$name = Utilities::clean_string($name, 50, '');

		if ( !$is_fullpath )
			$path = TEMPLATE_URL.$path;

		// convert $deps to an array if it is not an array
		if ( $deps != NULL and (array) $deps !== $deps )
			$deps = explode(',', preg_replace("/\s/", '', $deps) );


		wp_register_script( $name, $path, $deps, NULL, $in_footer );

	}

	/**
	 * clean_string()
	 *
	 * Creates URL friendly strings
	 */
	public static function clean_string($phrase, $maxLength=50, $sub='-') 
	{
	    $result = strtolower($phrase);
	    $result = preg_replace("/[^a-z0-9\s-]/", $sub, $result);
	    $result = trim(preg_replace("/[\s-]+/", " ", $result));
	    $result = trim(substr($result, 0, $maxLength));
	    $result = preg_replace("/\s/", $sub, $result);
	    return $result;
	}

	/**
	 * slice_string
	 *
	 * The start of the range is inclusive and the end is exclusive
	 *
	 * @param input (str) the string to be sliced up
	 * @param slice (mixed) can be a single character index, or a range separated by a colon.
	 */

	public static function slice_string($input, $slice) {



		if (is_int($slice)) {
			$start = $slice;
		} else { 
			$arg = explode(':', $slice);
			$start = intval($arg[0]);
		}

	    if ($start < 0) {
	        $start += strlen($input);
	    }
	    if (count($arg) === 1) {
	        return substr($input, $start, 1);
	    }
	    if (trim($arg[1]) === '') {
	        return substr($input, $start);
	    }
	    $end = intval($arg[1]);
	    if ($end < 0) {
	        $end += strlen($input);
	    }
	    return substr($input, $start, $end - $start);
	}

	/**
	 * twitterStyleDate()
	 * 
	 * Twitter style post dates // 트위터 스타일의 날짜 표시법
	 * i.e. instead of 'Posted 13 Jan 2011 at 7:03' it displays '3 hours ago'
	 * @param $rtime (mixed) 	str|integer representing the time. If it is a string it
	 * 							this function will attempt to converter it to its int 
	 *							time equivalent
	 */
	public static function twitterStyleDate($rtime) 
	{

		if ( is_string($rtime) ) {
			$t = strtotime($rtime);
		}

		$tmptime = time() - $t;

		if($tmptime < 0)
			$rtimeStr = "1 second ago";
		else if ($tmptime < 60)
			$rtimeStr = (int)$tmptime . __(" seconds ago", THEME_NAME);
		else if ($tmptime < 120)
			$rtimeStr = (int)($tmptime/60) . __(" minute ago", THEME_NAME);
		else if ($tmptime < 3600)
			$rtimeStr = (int)($tmptime/60) . __(" minutes ago", THEME_NAME);
		else if ($tmptime < 7200)
			$rtimeStr = (int)($tmptime/3600) . __(" hour ago", THEME_NAME);
		else if ($tmptime < 86400)
			$rtimeStr = (int)($tmptime/3600) . __(" hours ago", THEME_NAME);
		else if ($tmptime < 172800)
			$rtimeStr = (int)($tmptime/86400) . __(" day ago", THEME_NAME);
		else if ($tmptime < 604800)
			$rtimeStr = (int)($tmptime/86400) . __(" days ago", THEME_NAME);
		else
			$rtimeStr = date( 'M d Y, h:iA' ,$t);

		return $rtimeStr;
	}


	/** 
	 * self_uri()
	 * @return (str) the URL of the current page 
	 */
	public static function self_uri() 
	{
	    $url = 'http';
	    $script_name = '';

	    if (isset($_SERVER['REQUEST_URI'])):
	        $script_name = $_SERVER['REQUEST_URI'];

	    else:
	        $script_name = $_SERVER['PHP_SELF'];

	        if ($_SERVER['QUERY_STRING'] > ' '):
	            $script_name .= '?' . $_SERVER['QUERY_STRING'];

	        endif;
	    endif;

	        if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on')
	            $url .= 's';

	        $url .= '://';

	        if ($_SERVER['SERVER_PORT'] != '80'):
	            $url .= $_SERVER['HTTP_HOST'] . ':' . $_SERVER['SERVER_PORT'] . $script_name;

	        else:
	            $url .= $_SERVER['HTTP_HOST'] . $script_name;

	        endif;
		
	    return $url;
	}

	public static function see_registered_scripts() 
	{
		Utilities::debug($GLOBALS['wp_scripts']->registered);
	}

	public static function debug($obj)
	{
		echo '<pre>';
		var_dump($obj);
		echo '</pre>';
	}
}
?>